Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

AllCops:
  Exclude:
    - 'config/routes.rb'
    - 'db/**/*.rb'
    - 'node_modules/**/*'